use anyhow::{Context, Result};
use chrono::{DateTime, Datelike, FixedOffset, Timelike, Utc};
use serde::{Deserialize, Serialize};

use crate::models::{
    ContributionCalendar, ContributionDay, ContributionWeek, PinnedRepo, TimeDistribution,
    UserStats,
};

// Include GraphQL queries generated by build.rs from .graphql files
include!(concat!(env!("OUT_DIR"), "/queries.rs"));

/// Implements [[RFC-0002:C-GRAPHQL-CLIENT]]
pub struct GraphQLClient {
    token: String,
    client: reqwest::Client,
    pinned_repos: Vec<(String, String)>, // (owner, name) pairs
    timezone_offset: FixedOffset,        // User's timezone for time distribution
}

const GRAPHQL_ENDPOINT: &str = "https://api.github.com/graphql";
const REST_API_BASE: &str = "https://api.github.com";

#[derive(Debug, Serialize)]
struct GraphQLRequest<'a> {
    query: &'a str,
    variables: serde_json::Value,
}

// ===== User query response types =====

#[derive(Debug, Deserialize)]
struct UserResponse {
    data: Option<UserDataRoot>,
    errors: Option<Vec<GraphQLError>>,
}

#[derive(Debug, Deserialize)]
struct GraphQLError {
    message: String,
}

#[derive(Debug, Deserialize)]
struct UserDataRoot {
    user: Option<UserNode>,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
struct UserNode {
    id: String, // GitHub node ID for author filtering
    name: Option<String>,
    login: String,
    created_at: DateTime<Utc>,
    followers: CountNode,
    repositories: RepositoriesNode,
    contributions_collection: ContributionsCollectionNode,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
struct CountNode {
    total_count: u64,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
struct RepositoriesNode {
    total_count: u64,
    nodes: Vec<RepoStatsNode>,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
struct RepoStatsNode {
    stargazer_count: u64,
    fork_count: u64,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
struct ContributionsCollectionNode {
    total_commit_contributions: u64,
    total_pull_request_contributions: u64,
    total_issue_contributions: u64,
    contribution_calendar: CalendarNode,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
struct CalendarNode {
    total_contributions: u64,
    weeks: Vec<WeekNode>,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
struct WeekNode {
    contribution_days: Vec<DayNode>,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
struct DayNode {
    date: String,
    contribution_count: u64,
    contribution_level: String,
}

// ===== Repo query response types =====

#[derive(Debug, Deserialize)]
struct RepoResponse {
    data: Option<RepoDataRoot>,
    errors: Option<Vec<GraphQLError>>,
}

#[derive(Debug, Deserialize)]
struct RepoDataRoot {
    repository: Option<RepoNode>,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
struct RepoNode {
    name: String,
    description: Option<String>,
    stargazer_count: u64,
    fork_count: u64,
    primary_language: Option<LanguageNode>,
    default_branch_ref: Option<DefaultBranchRefNode>,
}

#[derive(Debug, Deserialize)]
struct LanguageNode {
    name: String,
    color: Option<String>,
}

#[derive(Debug, Deserialize)]
struct DefaultBranchRefNode {
    target: CommitTarget,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
struct CommitTarget {
    history: Option<HistoryNode>,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
struct HistoryNode {
    nodes: Vec<CommitNode>,
    total_count: u64,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
struct CommitNode {
    committed_date: DateTime<Utc>,
    additions: u64,
    deletions: u64,
}

impl GraphQLClient {
    /// Create a new GraphQL client
    /// `pinned_repos_str` is a comma-separated list of "owner/repo" pairs
    /// `timezone_str` is an offset like "+08:00" or "-05:00" (default: "+00:00")
    pub fn new(
        token: String,
        pinned_repos_str: Option<String>,
        timezone_str: Option<String>,
    ) -> Self {
        let client = reqwest::Client::new();
        let pinned_repos = pinned_repos_str
            .unwrap_or_default()
            .split(',')
            .filter_map(|s| {
                let s = s.trim();
                if s.is_empty() {
                    return None;
                }
                let parts: Vec<&str> = s.splitn(2, '/').collect();
                if parts.len() == 2 {
                    Some((parts[0].to_string(), parts[1].to_string()))
                } else {
                    eprintln!("warning: invalid pinned repo format: {s} (expected owner/repo)");
                    None
                }
            })
            .collect();

        // Parse timezone offset (e.g., "+08:00", "-05:00")
        let timezone_offset = timezone_str
            .as_deref()
            .and_then(|s| {
                // Try parsing as "+HH:MM" or "-HH:MM"
                if s.len() >= 6 {
                    let sign = if s.starts_with('-') { -1 } else { 1 };
                    let hours: i32 = s[1..3].parse().ok()?;
                    let mins: i32 = s[4..6].parse().ok()?;
                    let total_secs = sign * (hours * 3600 + mins * 60);
                    FixedOffset::east_opt(total_secs)
                } else {
                    None
                }
            })
            .unwrap_or_else(|| FixedOffset::east_opt(0).unwrap());

        Self {
            token,
            client,
            pinned_repos,
            timezone_offset,
        }
    }

    /// Fetch all user stats via GraphQL
    /// Implements [[RFC-0002:C-GRAPHQL-CLIENT]]
    pub async fn fetch_stats(&self, username: &str) -> Result<UserStats> {
        let now = Utc::now();
        let one_year_ago = now - chrono::Duration::days(365);

        // Fetch user profile and contributions
        let user = self.fetch_user(username, &one_year_ago, &now).await?;

        // Compute aggregates
        let total_stars: u64 = user
            .repositories
            .nodes
            .iter()
            .map(|r| r.stargazer_count)
            .sum();
        let total_forks: u64 = user.repositories.nodes.iter().map(|r| r.fork_count).sum();

        // Account age
        let age = now.signed_duration_since(user.created_at);
        let age_days = age.num_days().max(0) as u64;
        let age_years = age_days / 365;

        // Contribution calendar
        let calendar = ContributionCalendar {
            total_contributions: user
                .contributions_collection
                .contribution_calendar
                .total_contributions,
            weeks: user
                .contributions_collection
                .contribution_calendar
                .weeks
                .into_iter()
                .map(|w| ContributionWeek {
                    days: w
                        .contribution_days
                        .into_iter()
                        .map(|d| ContributionDay {
                            date: d.date,
                            contribution_count: d.contribution_count,
                            level: level_from_string(&d.contribution_level),
                        })
                        .collect(),
                })
                .collect(),
        };

        let streaks = calendar.compute_streaks();

        // Fetch pinned repos (user-configured, not GitHub pinned items)
        // Filter commits by the user's author ID
        let pinned_repos = if self.pinned_repos.is_empty() {
            None
        } else {
            let mut repos = Vec::new();
            for (owner, name) in &self.pinned_repos {
                match self.fetch_repo(owner, name, &one_year_ago, &user.id).await {
                    Ok(repo) => repos.push(repo),
                    Err(e) => eprintln!("warning: failed to fetch {owner}/{name}: {e:#}"),
                }
            }
            if repos.is_empty() { None } else { Some(repos) }
        };

        // Fetch time distribution from commit history (REST API)
        let time_distribution = match self.fetch_time_distribution(&user.login).await {
            Ok(dist) => Some(dist),
            Err(e) => {
                eprintln!("warning: failed to fetch time distribution: {e:#}");
                None
            }
        };

        Ok(UserStats {
            name: user.name,
            username: user.login,
            repos: user.repositories.total_count,
            stars: total_stars,
            forks: total_forks,
            followers: user.followers.total_count,
            commits: user.contributions_collection.total_commit_contributions,
            prs: user
                .contributions_collection
                .total_pull_request_contributions,
            issues: user.contributions_collection.total_issue_contributions,
            account_age_years: age_years,
            account_age_days: age_days,
            contribution_calendar: Some(calendar),
            streaks: Some(streaks),
            pinned_repos,
            time_distribution,
        })
    }

    async fn fetch_user(
        &self,
        username: &str,
        from: &DateTime<Utc>,
        to: &DateTime<Utc>,
    ) -> Result<UserNode> {
        let variables = serde_json::json!({
            "login": username,
            "from": from.to_rfc3339(),
            "to": to.to_rfc3339(),
        });

        let request = GraphQLRequest {
            query: USER_QUERY,
            variables,
        };

        let response = self
            .client
            .post(GRAPHQL_ENDPOINT)
            .header("Authorization", format!("Bearer {}", self.token))
            .header("User-Agent", "github-stats-typst")
            .json(&request)
            .send()
            .await
            .context("Failed to send GraphQL request")?;

        let status = response.status();
        if !status.is_success() {
            let body = response.text().await.unwrap_or_default();
            anyhow::bail!("GraphQL request failed with status {}: {}", status, body);
        }

        let gql_response: UserResponse = response
            .json()
            .await
            .context("Failed to parse user GraphQL response")?;

        if let Some(errors) = gql_response.errors {
            let msgs: Vec<_> = errors.iter().map(|e| e.message.as_str()).collect();
            anyhow::bail!("GraphQL errors: {}", msgs.join(", "));
        }

        gql_response
            .data
            .and_then(|d| d.user)
            .context("User not found")
    }

    async fn fetch_repo(
        &self,
        owner: &str,
        name: &str,
        since: &DateTime<Utc>,
        author_id: &str,
    ) -> Result<PinnedRepo> {
        let variables = serde_json::json!({
            "owner": owner,
            "name": name,
            "since": since.to_rfc3339(),
            "authorId": author_id,
        });

        let request = GraphQLRequest {
            query: REPO_QUERY,
            variables,
        };

        let response = self
            .client
            .post(GRAPHQL_ENDPOINT)
            .header("Authorization", format!("Bearer {}", self.token))
            .header("User-Agent", "github-stats-typst")
            .json(&request)
            .send()
            .await
            .context("Failed to send repo GraphQL request")?;

        let status = response.status();
        if !status.is_success() {
            let body = response.text().await.unwrap_or_default();
            anyhow::bail!("Repo GraphQL request failed: {}", body);
        }

        let gql_response: RepoResponse = response
            .json()
            .await
            .context("Failed to parse repo GraphQL response")?;

        if let Some(errors) = gql_response.errors {
            let msgs: Vec<_> = errors.iter().map(|e| e.message.as_str()).collect();
            anyhow::bail!("GraphQL errors: {}", msgs.join(", "));
        }

        let repo = gql_response
            .data
            .and_then(|d| d.repository)
            .context("Repository not found")?;

        let (additions, deletions, commits, last_date) =
            if let Some(ref branch) = repo.default_branch_ref {
                let history = branch.target.history.as_ref();
                let adds: u64 = history
                    .map(|h| h.nodes.iter().map(|c| c.additions).sum())
                    .unwrap_or(0);
                let dels: u64 = history
                    .map(|h| h.nodes.iter().map(|c| c.deletions).sum())
                    .unwrap_or(0);
                let count = history.map(|h| h.total_count).unwrap_or(0);
                // Get user's last commit date from the first node (most recent)
                let date = history
                    .and_then(|h| h.nodes.first())
                    .map(|c| c.committed_date.format("%Y-%m-%d").to_string());
                (adds, dels, count, date)
            } else {
                (0, 0, 0, None)
            };

        Ok(PinnedRepo {
            name: repo.name,
            description: repo.description,
            stars: repo.stargazer_count,
            forks: repo.fork_count,
            language: repo.primary_language.as_ref().map(|l| l.name.clone()),
            language_color: repo.primary_language.and_then(|l| l.color),
            recent_additions: additions,
            recent_deletions: deletions,
            recent_commits: commits,
            last_commit_date: last_date,
        })
    }

    /// Fetch commit time distribution using REST API search
    /// Returns a 24×7 grid of commit counts by hour and weekday
    async fn fetch_time_distribution(&self, username: &str) -> Result<TimeDistribution> {
        let tz_str = format!(
            "{:+03}:{:02}",
            self.timezone_offset.local_minus_utc() / 3600,
            (self.timezone_offset.local_minus_utc().abs() % 3600) / 60
        );
        let mut distribution = TimeDistribution::new(tz_str);

        // Track earliest and latest commit dates
        let mut earliest: Option<DateTime<FixedOffset>> = None;
        let mut latest: Option<DateTime<FixedOffset>> = None;

        // Fetch up to 1000 commits (10 pages of 100)
        for page in 1..=10 {
            let url = format!(
                "{}/search/commits?q=author:{}&sort=author-date&order=desc&per_page=100&page={}",
                REST_API_BASE, username, page
            );

            let response = self
                .client
                .get(&url)
                .header("Authorization", format!("Bearer {}", self.token))
                .header("User-Agent", "github-stats-typst")
                .header("Accept", "application/vnd.github+json")
                .send()
                .await
                .context("Failed to send commit search request")?;

            let status = response.status();
            if !status.is_success() {
                let body = response.text().await.unwrap_or_default();
                anyhow::bail!("Commit search failed with status {}: {}", status, body);
            }

            let search_result: CommitSearchResponse = response
                .json()
                .await
                .context("Failed to parse commit search response")?;

            if search_result.items.is_empty() {
                break; // No more results
            }

            for item in &search_result.items {
                if let Some(ref commit) = item.commit
                    && let Some(ref author) = commit.author {
                        // Parse the date and convert to user's timezone
                        if let Ok(utc_time) = DateTime::parse_from_rfc3339(&author.date) {
                            let local_time = utc_time.with_timezone(&self.timezone_offset);
                            let hour = local_time.hour() as u8;
                            // weekday(): Mon=0, Tue=1, ..., Sun=6
                            let weekday = local_time.weekday().num_days_from_monday() as u8;
                            distribution.add(hour, weekday);

                            // Track date range
                            match earliest {
                                None => earliest = Some(local_time),
                                Some(e) if local_time < e => earliest = Some(local_time),
                                _ => {}
                            }
                            match latest {
                                None => latest = Some(local_time),
                                Some(l) if local_time > l => latest = Some(local_time),
                                _ => {}
                            }
                        }
                    }
            }

            // If we got fewer than 100, we've reached the end
            if search_result.items.len() < 100 {
                break;
            }
        }

        // Set date range
        distribution.earliest_date = earliest.map(|d| d.format("%Y-%m-%d").to_string());
        distribution.latest_date = latest.map(|d| d.format("%Y-%m-%d").to_string());

        distribution.finalize();
        Ok(distribution)
    }
}

// REST API response types for commit search
#[derive(Debug, Deserialize)]
struct CommitSearchResponse {
    items: Vec<CommitSearchItem>,
}

#[derive(Debug, Deserialize)]
struct CommitSearchItem {
    commit: Option<CommitInfo>,
}

#[derive(Debug, Deserialize)]
struct CommitInfo {
    author: Option<CommitAuthor>,
}

#[derive(Debug, Deserialize)]
struct CommitAuthor {
    date: String,
}

/// Convert GitHub's contribution level string to a numeric level (0-4)
/// Implements [[RFC-0002:C-CONTRIBUTION-CALENDAR]]
fn level_from_string(level: &str) -> u8 {
    match level {
        "NONE" => 0,
        "FIRST_QUARTILE" => 1,
        "SECOND_QUARTILE" => 2,
        "THIRD_QUARTILE" => 3,
        "FOURTH_QUARTILE" => 4,
        _ => 0,
    }
}
